job1:
  stage: .pre
  script:
    - echo "pre"

job2:
  stage: .post
  script:
    - echo "post"
  after_script:
    - echo "after post"

job3:
  stage: build
  script:
    - echo "build"

job4:
  stage: deploy
  script:
    - echo "test"

job5:
  stage: deploy
  script:
    - echo "deploy"

send_email:
  stage: deploy
  script:
    - apt-get update && apt-get install -y mailutils
    - echo "Build succeeded!" | mail -s "Build Notification" edge27452696803@gmail.com